### ISSUE TITLE
Getting the state of a device

### ISSUE THREAD

**Issue by pijpijpij** [joneschrisg/android-system-core#6]
When getting the list of devices (with `JadbConnection.getDevices()`), ADB closes the connection (as per protocol), so the next call (to `JadbDevice.getState()`), fails with 

```
se.vidstige.jadb.JadbException: command failed: closed

    at se.vidstige.jadb.Transport.verifyResponse(Transport.java:39)
    at se.vidstige.jadb.JadbDevice.getState(JadbDevice.java:46)
```

That is also true with a device acquired with `JadbConnection.getAnyDevice()`.
There doesn't seem to be any other way getting hold of a device.

What gives? Are there circumstances in which  `JadbDevice.getState()` works?

PS: Thanks for this library. Installing packages work, so it does help quite a lot.

**Comment by pijpijpij** [comment]
Sorry, wrong place! :(
